export MOZ_ENABLE_WAYLAND=1
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export WLR_NO_HARDWARE_CURSORS=1
#export WLR_NO_HARDWARE_CURSORS=0
export WLR_RENDERER_ALLOW_SOFTWARE=1
MOD_WEBRENDER=1
GTK_THEME=Arc-Dark
QT_STYLE_OVERRIDE=kvantum-dark

PATH=${HOME}/.local/bin:${PATH}
TERM=wezterm
